version "4.12"

#include "LoRZScript/ammo.zs"
#include "LoRZScript/incinerator.zs"
#include "LoRZScript/heatwave.zs"

const DOOMRR_INCINERATOR_FLAME_DAMAGE = 5;
const DOOMRR_INCINERATOR_FLAME_VELOCITY = 40;
const DOOMRR_INCINERATOR_BURN_DAMAGE = 5;
const DOOMRR_INCINERATOR_BURN_RADIUS = 64;

const DOOMRR_HEATWAVE_RIPPER_DAMAGE = 10;
const DOOMRR_HEATWAVE_RIPPER_VELOCITY = 20;